[package]
name = "adventofcode2023"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "day01"
path = "day01/src/main.rs"

[[bin]]
name = "day02"
path = "day02/src/main.rs"

[[bin]]
name = "day03"
path = "day03/src/main.rs"
